### ISSUE TITLE
请问数据集会上传到谷歌云盘或者阿里云盘吗？

### ISSUE THREAD

**Issue by TCBocean** [ZYB0726/MKDNet#1]
因为大多数人都没有百度云的会员导致下载速度非常慢，希望官方能分享到其他云盘。万分感谢~

**Comment by ZYB0726** [comment]
数据集太大，谷歌云盘放不下。后期再想一下办法。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月15日(周二) 下午4:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ZYB0726/MKDNet] 请问数据集会上传到谷歌云盘或者阿里云盘吗？ (Issue #1)




 
因为大多数人都没有百度云的会员导致下载速度非常慢，希望官方能分享到其他云盘。万分感谢~
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZYB0726** [comment]
过几天有空看看阿里云能不能放下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月15日(周二) 下午4:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ZYB0726/MKDNet] 请问数据集会上传到谷歌云盘或者阿里云盘吗？ (Issue #1)




 
因为大多数人都没有百度云的会员导致下载速度非常慢，希望官方能分享到其他云盘。万分感谢~
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TCBocean** [comment]
好的，非常感谢~
