### ISSUE TITLE
跟踪模型百度网盘的提取码

### ISSUE THREAD

**Issue by kongbia** [ZYB0726/MKDNet#2]
您好，请问提供的训练模型的百度网盘提取码是多少？

**Comment by ZYB0726** [comment]
模型在实验室电脑里&nbsp; 过两天开学回校&nbsp; 我会传上去



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月17日(周四) 上午10:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ZYB0726/MKDNet] 跟踪模型百度网盘的提取码 (Issue #2)




 
您好，请问提供的训练模型的百度网盘提取码是多少？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kongbia** [comment]
> 模型在实验室电脑里&nbsp; 过两天开学回校&nbsp; 我会传上去
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年2月17日(周四) 上午10:25 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [ZYB0726/MKDNet] 跟踪模型百度网盘的提取码 (Issue #2) 您好，请问提供的训练模型的百度网盘提取码是多少？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

好的，非常感谢！

**Comment by ZYB0726** [comment]
已传

**Comment by xiaofa-jpg** [comment]
您好，能麻烦您再重新上传一下模型权重吗，目前的网盘链接显示过期

**Comment by xiaofa-jpg** [comment]
您好，能麻烦您再重新上传一下跟踪模型文件吗，目前百度网盘里的似乎过期了

**Comment by ZYB0726** [comment]
已传
