### ISSUE TITLE
数据集部分文件不存在

### ISSUE THREAD

**Issue by Mr-IronMan** [ZYB0726/MKDNet#3]
https://github.com/users/TOT-BENCHMARK/projects/1#card-58945129
用百度网盘打开该网址，显示“转存文件失败：部分文件不存在”

**Comment by ZYB0726** [comment]
我这边打开是正常的  今天我把数据集文件压缩一下 明天再重新传一下

**Comment by Mr-IronMan** [comment]
谢谢您，可能打包成一整个文件后下载起来更方便

**Comment by ZYB0726** [comment]
> 谢谢您，可能打包成一整个文件后下载起来更方便
已经上传了 你再试一下
