### ISSUE TITLE
Normalized Precision 评估结果的疑问

### ISSUE THREAD

**Issue by xyl-507** [ZYB0726/MKDNet#7]
作者您好，感谢你们的巨大感谢！

我在跑你们数据集LaTOT的工具箱时，想eval一下Normalized Precision，于是令 norm_dst = true;
但得到的结果与您们的论文差距很大，不知道是哪里出了问题？
希望能得到你们的指点，十分感谢！
 
![error_OPE_threshold](https://user-images.githubusercontent.com/69385203/204134920-8e8cd7f4-d509-4286-b99e-2f1181ba172c.png)

**Comment by ZYB0726** [comment]
要改一下阈值&nbsp; 归一化结果的阈值是21&nbsp; 目前是6



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月27日(周日) 晚上8:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ZYB0726/MKDNet] Normalized Precision 评估结果的疑问 (Issue #7)




 
作者您好，感谢你们的巨大感谢！
 
我在跑你们数据集LaTOT的工具箱时，想eval一下Normalized Precision，于是令 norm_dst = true;
 但得到的结果与您们的论文差距很大，不知道是哪里出了问题？
 希望能得到你们的指点，十分感谢！

**Comment by xyl-507** [comment]
@ZYB0726 好的，十分感谢！
